# Generated by Django 4.1.2 on 2022-10-26 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cannibas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowerRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lfd_rank', models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Mediocre', 'Mediocre'), ('Avoid', 'Avoid')], max_length=15, null=True)),
                ('dlf_rank', models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Mediocre', 'Mediocre'), ('Avoid', 'Avoid')], max_length=15, null=True)),
                ('hrf_rank', models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Mediocre', 'Mediocre'), ('Avoid', 'Avoid')], max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('Compact', 'Compact')], default='Compact', max_length=10)),
                ('veg_state', models.CharField(max_length=50)),
                ('flower_state', models.CharField(max_length=50)),
                ('yields', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=50)),
                ('cannibas_store', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Seed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('indica_percent', models.IntegerField()),
                ('sative_percent', models.IntegerField()),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy')], default='Easy', max_length=10)),
                ('thc', models.IntegerField()),
                ('cbd', models.IntegerField()),
                ('seed_producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cannibas.producer')),
            ],
        ),
        migrations.CreateModel(
            name='StoreCannibas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('producer', models.CharField(max_length=25)),
            ],
        ),
        migrations.DeleteModel(
            name='SeedProducer',
        ),
        migrations.AddField(
            model_name='plant',
            name='seed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cannibas.seed'),
        ),
        migrations.AddField(
            model_name='flowerrank',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cannibas.storecannibas'),
        ),
    ]
